version: "3.8"

services:
  polybot:
    image: ${IMG_NAME}
    container_name: polybot-dev
    ports:
      - "8443:8443"
    environment:
      - ENV=development
      - AWS_REGION=us-west-1
      - AWS_S3_BUCKET=deema-polybot-dev-images
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_APP_URL=${BOT_APP_URL}
      - YOLO_URL=${YOLO_URL}
      - STORAGE_TYPE=${STORAGE_TYPE}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL_DEV}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
    depends_on:
      - otelcol
    restart: unless-stopped

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcol-dev
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    command: [ "--config=/etc/otelcol/config.yaml" ]
    network_mode: host
    restart: always
