version: "3.8"

services:
  polybot:
    image: ${IMG_NAME}   # Use the image from .env file
    container_name: polybot-prod
    ports:
      - "8443:8443"
    environment:
      - ENV=prod
      - AWS_REGION=us-west-1
      - AWS_S3_BUCKET=deema-polybot-images
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}   # Use env var from .env
      - BOT_APP_URL=${BOT_APP_URL}
      - YOLO_URL=${YOLO_URL}

    depends_on:
      - otelcol
    restart: unless-stopped

  otelcol:
    image: otel/opentelemetry-collector:latest
    container_name: otelcol-prod
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    command: ["--config=/etc/otelcol-config.yaml"]



  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana