version: "3.8"

services:
  polybot:
    image: ${IMG_NAME}   # Use the image from .env file
    container_name: polybot-prod
    ports:
      - "8443:8443"

    environment:
      - ENV=production
      - AWS_REGION=us-west-1
      - AWS_S3_BUCKET=deema-polybot-images
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_APP_URL=${BOT_APP_URL}
      - YOLO_URL=${YOLO_URL}
      - CERT_PATH=${CERT_PATH}
      - STORAGE_TYPE=${STORAGE_TYPE}
      - CERT_PATH=${CERT_PATH}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL_PROD}

    volumes:
      - /etc/letsencrypt/live/proxydeema.fursa.click/fullchain.pem:/app/polybot/certs/fullchain.pem  # ✅ USE the real cert

    depends_on:
      - otelcol
    restart: unless-stopped

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcol-prod
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    command: [ "--config=/etc/otelcol/config.yaml" ]
    network_mode: host
    restart: always
