version: "3.8"

services:
  polybot:
    build: .
    container_name: polybot-prod
    ports:
      - "8443:8443"
    environment:
      - ENV=prod
      - AWS_REGION=us-west-1
      - AWS_S3_BUCKET=deema-polybot-images
      - TELEGRAM_BOT_TOKEN=7646100933:AAF2IatgO44CwiCiOnZnP28uIejRLGwifT0
      - BOT_APP_URL=https://proxydeema.fursa.click:8443/7646100933:AAF2IatgO44CwiCiOnZnP28uIejRLGwifT0/
    depends_on:
      - otelcol
    restart: unless-stopped

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otelcol-prod
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
    environment:
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    network_mode: host
    restart: unless-stopped
