name: Deploy Polybot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEEMA_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          echo "Scanning EC2 host..."
          ssh-keyscan -H ${{ secrets.POLYBOT_HOST }} >> ~/.ssh/known_hosts

      - name: Copy deploy.sh to EC2
        run: |
          echo "Copying deploy.sh to EC2..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $GITHUB_WORKSPACE/deploy.sh ubuntu@${{ secrets.POLYBOT_HOST }}:/tmp/deploy.sh

      - name: Run deploy.sh on EC2
        run: |
          echo "Running deploy.sh on EC2..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.POLYBOT_HOST }} 'bash /tmp/deploy.sh'
