# .github/workflows/deploy-prod.yaml
name: Polybot Deploy Prod

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH and deploy to Prod EC2
        env:
          PRIVATE_KEY: ${{ secrets.DEEMA_KEY }}
          EC2_HOST: ${{ secrets.EC2_PROD_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}
        run: |
          echo "$PRIVATE_KEY" > key.pem
          chmod 400 key.pem

          echo "🔐 Connecting to $EC2_USER@$EC2_HOST..."
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
            cd /home/ubuntu/polybot-prod || git clone https://github.com/DeemaAbuHwaij/PolybotService.git polybot-prod && cd polybot-prod

            git checkout main
            git pull origin main

            echo "📝 Writing .env file..."
            echo "IMG_NAME=${{ inputs.image }}" > .env
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}" >> .env
            echo "TELEGRAM_APP_URL=proxydeema.fursa.click" >> .env

            echo "🐳 Deploying using Docker Compose..."
            docker compose -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.prod.yaml up -d --remove-orphans
          EOF
