name: Yolo unittesting

on:
  pull_request:
    branches:
      - main

jobs:
  TestImgProcessingChatbotApp:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r polybot/requirements.txt

      - name: Test filters
        run: |
          echo -e "\n\nTesting concat()\n"
          python -m polybot.test.test_concat

          echo -e "\n\nTesting rotate()\n"
          python -m polybot.test.test_rotate

          echo -e "\n\nTesting salt_n_pepper()\n"
          python -m polybot.test.test_salt_n_pepper

          echo -e "\n\nTesting segment()\n"
          python -m polybot.test.test_segment

          echo -e "\n\nTesting detect()\n"
          python -m polybot.test.test_detect

      - name: Test bot
        run: |
          python -m polybot.test.test_telegram_bot
